version: '3.8'
services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data_container:/data/db
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data_container:
